---
- name: This is a apache setup playbook
  hosts: "all"

  tasks:
    - name: Installing Apache application package
      yum:
        name: httpd
        state: present
    - name: Configuring Home page
      copy:
        dest: "/var/www/html/index.html"
        content: "<h1>This website is created using Ansible</h1>"
    - name: Start my Apache application
      service:
        name: httpd
        state: started
        enabled: true   
